from django.urls import path
from .views import (
    FeedListView,
    ReportCreateView,
    PostLikeView,
    PostCommentListCreateView,
    StoryListCreateView,
    MediaUploadView,
    StoryViewTrackingView,
    PostSaveView,
    PostShareView,
    PostRepostView,
    MediaListView,
    MediaDeleteView,
    ModerationQueueView,
    CommentModerationQueueView,
    ModerationActionView,
    DiscoverView,
    MaadiRecommendView,
)

urlpatterns = [
    path('', FeedListView.as_view(), name='feed-list-create'),
    path('posts/', FeedListView.as_view(), name='post-list-create'),
    path('upload/', MediaUploadView.as_view(), name='media-upload'),
    path('posts/<uuid:post_id>/report/', ReportCreateView.as_view(), name='report-post'),
    path('comments/<uuid:comment_id>/report/', ReportCreateView.as_view(), name='report-comment'),
    path('posts/<uuid:post_id>/like/', PostLikeView.as_view(), name='post-like'),
    path('posts/<uuid:post_id>/save/', PostSaveView.as_view(), name='post-save'),
    path('posts/<uuid:post_id>/share/', PostShareView.as_view(), name='post-share'),
    path('posts/<uuid:post_id>/repost/', PostRepostView.as_view(), name='post-repost'),
    path('posts/<uuid:post_id>/comments/', PostCommentListCreateView.as_view(), name='post-comments'),
    path('stories/', StoryListCreateView.as_view(), name='story-list-create'),
    path('stories/<uuid:story_id>/view/', StoryViewTrackingView.as_view(), name='story-view-track'),
    path('media/', MediaListView.as_view(), name='media-list'),
    path('media/<uuid:media_id>/', MediaDeleteView.as_view(), name='media-delete'),
    path('moderation/queue/', ModerationQueueView.as_view(), name='moderation-queue'),
    path('moderation/comments/queue/', CommentModerationQueueView.as_view(), name='comment-moderation-queue'),
    path('moderation/<str:target_type>/<uuid:target_id>/<str:action>/', ModerationActionView.as_view(), name='moderation-action'),
    path('discover/', DiscoverView.as_view(), name='discover'),
]
