# Generated by Django 6.0.7 on 2026-07-15 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalyticsdaily',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='feed.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatars', to='feed.mediaasset'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='accounts_cu_created_35a2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='authprovider',
            index=models.Index(fields=['provider', 'provider_user_id'], name='accounts_au_provide_55c869_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='authprovider',
            unique_together={('provider', 'provider_user_id')},
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker', 'blocked'], name='accounts_bl_blocker_746a2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followee', '-created_at'], name='accounts_fo_followe_ad6679_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
        migrations.AlterUniqueTogether(
            name='partnerdailyanalytics',
            unique_together={('partner', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='postanalyticsdaily',
            unique_together={('post', 'day')},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['username'], name='accounts_pr_usernam_a5e02d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx'),
        ),
    ]
