# Generated by Django 6.0.7 on 2026-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='partner_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
