# Generated by Django 6.0.7 on 2026-07-15 14:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du filtre')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('culture_traditions', 'Culture & Traditions'), ('lieux_patrimoine', 'Lieux & Patrimoine'), ('joj_2026', 'JOD Dakar 2026'), ('nature_faune', 'Nature & Faune')], default='joj_2026', max_length=50)),
                ('sdk_effect_id', models.CharField(help_text='Identifiant du pack Banuba/DeepAR côté CDN', max_length=255)),
                ('file_url', models.URLField(max_length=500, verbose_name="Lien vers l'asset 3D / Filtre")),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Lieu exclusif')),
                ('radius_meters', models.PositiveIntegerField(default=500, verbose_name='Rayon de disponibilité (mètres)')),
                ('is_geolocated', models.BooleanField(default=False)),
                ('is_time_limited', models.BooleanField(default=False)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name="Disponible sur l'application")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_geolocated'], name='ar_filters__is_acti_90fbda_idx'), models.Index(fields=['category'], name='ar_filters__categor_76e2f4_idx')],
            },
        ),
    ]
