"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys

from dotenv import load_dotenv
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / 'apps'))

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-2pf428z&ym-oz3s$he^&ys!qb3&o)-*n-)$jxkqbmda)=5#bgm')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_filters',
    'apps.accounts',
    'apps.feed',
    'apps.ar_filters',
    'apps.chat',
    'apps.geo',
    'apps.notifications',
    # NOTE: l'app `filters` est un squelette vide (doublon de `ar_filters`).
    # Retirée de INSTALLED_APPS tant qu'elle n'est pas implémentée.
    # 'apps.filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.RateLimitMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'  # <-- Ajoute cette ligne !

# Configuration de Channels (Redis pour le dev et la production)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')],
        },
    },
}

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('POSTGRES_DB', 'discover_db'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password_discover_2026'),
        'HOST': os.environ.get('POSTGRES_HOST', '/var/run/postgresql'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# Quand PostGIS/GDAL seront installés sur la machine, repasser sur :
# 'ENGINE': 'django.contrib.gis.db.backends.postgis',
# 'NAME': 'discover_db',
# 'USER': 'postgres',
# 'PASSWORD': 'password_discover_2026',
# 'HOST': '127.0.0.1',
# 'PORT': '5435',


# Redis cache (fallback to LocMemCache if Redis is unavailable)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'discover-senegal-cache',
    }
}
try:
    import redis
    redis_client = redis.Redis.from_url(os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'))
    redis_client.ping()
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        }
    }
except Exception:
    pass

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Les modèles définissent explicitement une PK UUIDField ; le champ auto par défaut
# (utilisé par les M2M intermédiaires implicites d'AbstractUser) reste un AutoField.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
REDIS_URL = os.environ.get('REDIS_URL', CELERY_BROKER_URL)

try:
    from celery.schedules import crontab
    CELERY_BEAT_SCHEDULE = {
        'purge-expired-stories-every-hour': {
            'task': 'feed.tasks.purge_expired_stories',
            'schedule': crontab(minute=0),
        },
        'check-report-threshold-every-6-hours': {
            'task': 'feed.tasks.check_report_threshold',
            'schedule': crontab(minute=0, hour='*/6'),
        },
    }
except Exception:
    CELERY_BEAT_SCHEDULE = {}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'accounts.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Discover Sénégal API',
    'DESCRIPTION': 'API du réseau social Discover Sénégal pour les JOJ Dakar 2026',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVERS': [
        {'url': 'http://127.0.0.1:8000', 'description': 'Serveur Local'},
        {'url': 'https://api.discover-senegal.sn', 'description': 'Serveur de Production'},
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),     # Jeton d'accès
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # Jeton de rafraîchissement
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

if os.environ.get('USE_POSTGIS') == 'True':
    GDAL_LIBRARY_PATH = os.environ.get('GDAL_LIBRARY_PATH', '/usr/lib/x86_64-linux-gnu/libgdal.so')
    GEOS_LIBRARY_PATH = os.environ.get('GEOS_LIBRARY_PATH', '/usr/lib/x86_64-linux-gnu/libgeos_c.so')

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",
    "http://localhost:3000",
    "http://127.0.0.1:8081",
]

# Rate limiting configuration
RATE_LIMITS = {
    'feed': {'requests': 1000, 'window': 3600},
    'moderation': {'requests': 200, 'window': 3600},
    'notifications': {'requests': 500, 'window': 3600},
}

# Cloudflare R2 / django-storages
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'discover-senegal-media')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'auto')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', 'https://<ACCOUNT_ID>.r2.cloudflarestorage.com')
AWS_S3_USE_SSL = True
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = 'public-read'
MEDIA_URL = f'https://{os.environ.get("AWS_STORAGE_BUCKET_NAME", "discover-senegal-media")}.r2.cloudflarestorage.com/'

# OAuth settings (placeholders - prêts à être configurés)
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')
APPLE_OAUTH_SERVICE_ID = os.environ.get('APPLE_OAUTH_SERVICE_ID', '')
APPLE_OAUTH_KEY_ID = os.environ.get('APPLE_OAUTH_KEY_ID', '')
APPLE_OAUTH_TEAM_ID = os.environ.get('APPLE_OAUTH_TEAM_ID', '')
APPLE_OAUTH_PRIVATE_KEY = os.environ.get('APPLE_OAUTH_PRIVATE_KEY', '')

# Firebase Admin SDK (placeholder - prêt à être connecté)
FIREBASE_CREDENTIALS_PATH = os.environ.get('FIREBASE_CREDENTIALS_PATH', '')
FIREBASE_ENABLED = bool(FIREBASE_CREDENTIALS_PATH)

# Maadi AI (déjà présent dans feed/services.py, ajout des settings par défaut)
MAADI_AI_URL = os.environ.get('MAADI_AI_URL', 'http://localhost:8001/maadi/recommend')
MAADI_AI_TIMEOUT = int(os.environ.get('MAADI_AI_TIMEOUT', '300')) / 1000.0  # secondes
# Active le mock de modération Maadi (mots bannis + aléatoire) au lieu de l'appel réseau.
# Mettre MAADI_MOCK=False en production une fois le service Maadi réellement disponible.
MAADI_MOCK = os.environ.get('MAADI_MOCK', 'True').lower() in ('1', 'true', 'yes', 'on')