from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from rest_framework_simplejwt.views import TokenObtainPairView
from drf_spectacular.types import OpenApiTypes
from .views import (
    RegisterView,
    UserProfileView,
    PartnerAnalyticsListView,
    PostAnalyticsDailyListView,
    OAuthLoginView,
    PhoneLoginView,
    PhoneRegisterRequestView,
    PhoneRegisterView,
    ProfileView,
    FollowView,
    CertifiedBadgeView,
    LogoutView,
    PasswordChangeView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    UserSearchView,
    ConsentToggleView,
    BlockView,
    AdminUserListView,
    AdminUserDetailView,
    AdminARFilterListView,
    AdminARFilterDetailView,
    AdminBroadcastView,
)
from .jwt_serializers import EmailTokenObtainPairView
from .auth_views import verify_token

urlpatterns = [
    path('auth/register/', RegisterView.as_view(), name='auth_register'),
    path('auth/login/', EmailTokenObtainPairView.as_view(), name='auth_login'),
    path('auth/login/phone/', PhoneLoginView.as_view(), name='auth_login_phone'),
    path('auth/register/phone/request/', PhoneRegisterRequestView.as_view(), name='auth_phone_register_request'),
    path('auth/register/phone/', PhoneRegisterView.as_view(), name='auth_phone_register'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='auth_token_refresh'),
    path('auth/logout/', LogoutView.as_view(), name='auth_logout'),
    path('auth/password/change/', PasswordChangeView.as_view(), name='auth_password_change'),
    path('auth/password/reset/', PasswordResetRequestView.as_view(), name='auth_password_reset'),
    path('auth/password/reset/confirm/', PasswordResetConfirmView.as_view(), name='auth_password_reset_confirm'),
    path('auth/oauth/<str:provider>/', OAuthLoginView.as_view(), name='auth_oauth'),
    path('auth/verify/', verify_token, name='auth_verify'),
    path('users/me', UserProfileView.as_view(), name='user-profile-me'),
    path('users/me/profile', ProfileView.as_view(), name='user-profile'),
    path('users/<uuid:user_id>/', ProfileView.as_view(), name='user-profile-public'),
    path('users/search/', UserSearchView.as_view(), name='user-search'),
    path('users/<uuid:user_id>/follow/', FollowView.as_view(), name='user-follow'),
    path('users/<uuid:user_id>/certified/', CertifiedBadgeView.as_view(), name='user-certified'),
    path('users/<uuid:user_id>/block/', BlockView.as_view(), name='user-block'),
    path('users/me/consent/', ConsentToggleView.as_view(), name='user-consent'),
    path('partners/analytics', PartnerAnalyticsListView.as_view(), name='partner-analytics'),
    path('partners/analytics/posts', PostAnalyticsDailyListView.as_view(), name='partner-post-analytics'),
    path('admin/users/', AdminUserListView.as_view(), name='admin-user-list'),
    path('admin/users/<uuid:user_id>/', AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('admin/ar-filters/', AdminARFilterListView.as_view(), name='admin-arfilter-list'),
    path('admin/ar-filters/<uuid:pk>/', AdminARFilterDetailView.as_view(), name='admin-arfilter-detail'),
    path('admin/notifications/broadcast/', AdminBroadcastView.as_view(), name='admin-notification-broadcast'),
]
