# Generated by Django 6.0.7 on 2026-07-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_repost_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='has_watermark',
            field=models.BooleanField(default=False),
        ),
    ]
