# Generated by Django 6.0.7 on 2026-07-15 14:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ar_filters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('tourist', 'Touristique'), ('cultural', 'Culturel'), ('gastronomy', 'Gastronomique'), ('sport', 'Sportif'), ('joj_2026', 'JOD Dakar 2026')], default='tourist', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('unlock_radius_meters', models.PositiveIntegerField(default=200)),
                ('partner_establishment_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'is_active'], name='geo_pointof_categor_98efe2_idx'), models.Index(fields=['created_at'], name='geo_pointof_created_6d9860_idx')],
            },
        ),
        migrations.CreateModel(
            name='POIFilterUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_unlocks', to='ar_filters.arfilter')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_unlocks', to='geo.pointofinterest')),
            ],
            options={
                'indexes': [models.Index(fields=['poi', 'ar_filter'], name='geo_poifilt_poi_id_7ca569_idx')],
                'unique_together': {('poi', 'ar_filter')},
            },
        ),
    ]
